#!/bin/bash
set -euo pipefail

# autodocs setup wizard
# Generates config, renders prompts, and sets up scheduling.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$SCRIPT_DIR/templates"

echo "=== autodocs setup ==="
echo ""

# --- Step 1: Paths ---

read -rp "Path to your git repo (e.g., ~/Documents/my-repo): " REPO_DIR
REPO_DIR="${REPO_DIR/#\~/$HOME}"
if [ ! -d "$REPO_DIR/.git" ]; then
  echo "Error: $REPO_DIR is not a git repository."
  exit 1
fi

read -rp "Output directory for reports (e.g., ~/Documents/autodocs-output): " OUTPUT_DIR
OUTPUT_DIR="${OUTPUT_DIR/#\~/$HOME}"
mkdir -p "$OUTPUT_DIR"

echo ""

# --- Step 2: ADO details ---

read -rp "ADO organization name: " ADO_ORG
read -rp "ADO project name: " ADO_PROJECT
read -rp "ADO repository name: " ADO_REPO

echo ""
echo "Resolving repository GUID..."
echo "You can either:"
echo "  1. Let Claude Code resolve it (requires ADO MCP access)"
echo "  2. Enter it manually (find in ADO → Project Settings → Repositories → URL)"
echo ""
read -rp "Enter repo GUID (or press Enter to resolve via Claude Code): " ADO_REPO_ID

if [ -z "$ADO_REPO_ID" ]; then
  ADO_REPO_ID=$(cd "$REPO_DIR" && claude -p "Call mcp__azure-devops__repo_get_repo_by_name_or_id with project=$ADO_PROJECT, repositoryNameOrId=$ADO_REPO. Return ONLY the repository ID (GUID), nothing else." \
    --allowedTools "mcp__azure-devops__repo_get_repo_by_name_or_id" \
    --output-format text 2>/dev/null | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1) || true

  if [ -z "$ADO_REPO_ID" ]; then
    echo "Error: Could not resolve repo GUID. Enter it manually."
    read -rp "Repo GUID: " ADO_REPO_ID
  else
    echo "Resolved: $ADO_REPO_ID"
  fi
fi

echo ""

# --- Step 3: Owner ---

read -rp "Your name (feature owner): " OWNER_NAME
read -rp "Your email: " OWNER_EMAIL
read -rp "Your ADO ID (GUID, find in ADO profile): " OWNER_ADO_ID

echo ""

# --- Step 4: Feature ---

read -rp "Feature/area name (e.g., Channel Pages, Auth, Search): " FEATURE_NAME

echo ""

# --- Step 5: Telemetry ---

read -rp "Use Kusto telemetry? (y/n): " USE_TELEMETRY
TELEMETRY_ENABLED="false"
if [[ "$USE_TELEMETRY" =~ ^[Yy] ]]; then
  TELEMETRY_ENABLED="true"
fi

echo ""

# --- Step 6: Schedule ---

read -rp "Daily sync hour (UTC, 0-23, default 17): " SCHEDULE_HOUR
SCHEDULE_HOUR="${SCHEDULE_HOUR:-17}"

echo ""

# --- Step 7: Generate config ---

CONFIG_FILE="$OUTPUT_DIR/config.yaml"
if [ -f "$CONFIG_FILE" ]; then
  echo "Config already exists at $CONFIG_FILE — skipping generation."
  echo "Delete it and re-run setup to regenerate."
else
  cat > "$CONFIG_FILE" <<EOF
# autodocs configuration — generated by setup.sh
# Edit this file to customize team, paths, queries, and doc mappings.
# Changes take effect on the next sync (no need to re-run setup).

ado:
  org: "$ADO_ORG"
  project: "$ADO_PROJECT"
  repo: "$ADO_REPO"
  repo_id: "$ADO_REPO_ID"

owner:
  name: "$OWNER_NAME"
  email: "$OWNER_EMAIL"
  ado_id: "$OWNER_ADO_ID"

# Add your team members here
team_members: []
  # - name: "Teammate"
  #   email: "teammate@company.com"
  #   ado_id: "00000000-..."

# Paths that indicate a PR is relevant to your feature
relevant_paths: []
  # - packages/your-feature/

relevant_pattern: ""
  # e.g., "*your-feature*"

telemetry:
  enabled: $TELEMETRY_ENABLED
  # cluster: "your-cluster.kusto.windows.net"
  # database: "your-database-id"
  # queries: []

# Reference docs for drift detection (optional)
# docs: []

last_verified: "$(date +%Y-%m-%d)"
EOF
  echo "Config generated at $CONFIG_FILE"
  echo "Edit it to add team members, relevant paths, queries, and doc mappings."
fi

echo ""

# --- Step 8: Render prompts ---

export OUTPUT_DIR REPO_DIR FEATURE_NAME OWNER_NAME SCHEDULE_HOUR

echo "Rendering prompts..."
envsubst '${OUTPUT_DIR} ${FEATURE_NAME} ${OWNER_NAME}' < "$TEMPLATES_DIR/sync-prompt.md" > "$OUTPUT_DIR/sync-prompt.md"
envsubst '${OUTPUT_DIR}' < "$TEMPLATES_DIR/drift-prompt.md" > "$OUTPUT_DIR/drift-prompt.md"

echo "Rendering wrapper script..."
envsubst '${OUTPUT_DIR} ${REPO_DIR}' < "$TEMPLATES_DIR/sync.sh" > "$OUTPUT_DIR/autodocs-sync.sh"
chmod +x "$OUTPUT_DIR/autodocs-sync.sh"

echo "Rendering manual trigger..."
cat > "$OUTPUT_DIR/autodocs-now" <<EOF
#!/bin/bash
exec "$OUTPUT_DIR/autodocs-sync.sh"
EOF
chmod +x "$OUTPUT_DIR/autodocs-now"

# --- Step 9: Render schedule ---

if [[ "$(uname)" == "Darwin" ]]; then
  PLIST_DIR="$HOME/Library/LaunchAgents"
  PLIST_FILE="$PLIST_DIR/com.autodocs.sync.plist"
  mkdir -p "$PLIST_DIR"

  envsubst '${OUTPUT_DIR} ${SCHEDULE_HOUR}' < "$TEMPLATES_DIR/com.autodocs.sync.plist" > "$PLIST_FILE"

  echo ""
  echo "launchd plist written to $PLIST_FILE"
  echo "To activate: launchctl load $PLIST_FILE"
else
  echo ""
  echo "Add this to your crontab (crontab -e):"
  echo "0 $SCHEDULE_HOUR * * * $OUTPUT_DIR/autodocs-sync.sh"
fi

# --- Done ---

echo ""
echo "=== Setup complete ==="
echo ""
echo "Next steps:"
echo "  1. Edit $CONFIG_FILE — add team members, relevant paths, and queries"
echo "  2. Copy your reference docs to $OUTPUT_DIR/"
echo "  3. Test manually: $OUTPUT_DIR/autodocs-now"
echo "  4. Activate daily schedule (see above)"
echo ""
echo "For configuration help: https://github.com/msiric/autodocs/blob/main/docs/configuration.md"
